#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 30 10:14:42 2019

@author: maarten
"""

from keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()