version: '2.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  tensorflow:
    image: mds-tensorflow:latest
    runtime: nvidia
    mem_limit: 12g
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
      # - KERAS_HOME=/keras
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - /data/maarten.schermer/data:/data
      - /data/maarten.schermer/deep-learning-tests/code:/code
      - /data/maarten.schermer/keras:/root/.keras
