FROM tensorflow/tensorflow:1.11.0-gpu-py3
MAINTAINER maarten schermer "maarten.schermer@naturalis.nl"

COPY requirements.txt /app/
WORKDIR /app

RUN pip install -r requirements.txt

RUN apt-get update && apt-get --no-install-recommends -y install tmux vim

CMD [ "bash" ]
