version: '2.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  python:
    image: maarten-python:latest
    runtime: nvidia
    mem_limit: 12g
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    image: maarten-python:latest
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - /data/maarten.schermer/data:/data
      - /data/maarten.schermer/deep-learning-tests/code:/code
      # - /home/maarten/Documents/ai/phase02:/code

networks:
  web:
    external: true
