version: '2.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  tensorflow:
    image: mds-tensorflow:latest
    runtime: nvidia
    mem_limit: 12g
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
      # - KERAS_HOME=/keras
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - /data/maarten.schermer/data:/data
      - /data/maarten.schermer/deep-learning-tests/code:/code
      - /data/maarten.schermer/keras:/root/.keras

  api:
    image: mds-api:latest
    runtime: nvidia
    mem_limit: 12g
    ports:
      - "8090:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=3
      # - KERAS_HOME=/keras
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - /data/maarten.schermer/keras:/root/.keras
      - /data/maarten.schermer/data:/data
      - /data/maarten.schermer/deep-learning-tests/code:/code
      - /data/maarten.schermer/api-log/:/log

  webserver:
    image: mds-webserver:latest
    ports:
      - "8091:80"
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - /data/maarten.schermer/data:/data
      - ../webserver:/var/www/html

  tensorboard:
    image: mds-tensorboard:latest
    ports:
      - "9876:6006"
    env_file:
      - .env
    logging: *default-logging
    volumes:
      - ${PROJECT_ROOT}/log:/log


