project_name: corvidae
project_root: /storage/data/corvidae/

# all other paths should be relative to project_root



dwca_infile:
  file: data/Occurrence.txt
  encoding: utf-8-sig
  headers:
    id: catalogNumber
    name: scientificName
    images: associatedMedia




#test_image_folder: tests/
test_image_folder: images/
log_folder: log/

models:
  basename: corvidae_{model_architecture}
  folder: models/

images_per_class_minimum: 150

# reg exp for parsing actual filename from URL
image_url_path_parse:
  reg_exp: ^(/file/id/)(.*)(/format/)(.*)$
  name_index: 1

image_download:
  folder: images/
  default_extension: jpg
  # if downloaded images don't have one of these extensions, they automatically get 'default_extension'
  expected_extensions:
    - jpg
    - jpeg

image_lists:
  all:
    file: data/imagelist.csv
    encoding: utf-8-sig
    col_class: label
    col_image: image
  downloaded:
    file: data/images_downloaded.csv
  corrupt:
    file: data/corrupt_images.csv
  classes:
    file: data/classes.csv
  train:
    file: data/images_train.csv
  test:
    file: data/images_test.csv
