project_name: corvidae
project_root: /storage/data/corvidae/

# all other paths should be relative to project_root

dwca_infile:
  name: data/Occurrence.txt
  encoding: utf-8-sig
  headers:
    id: catalogNumber
    name: scientificName
    images: associatedMedia

# reg exp for parsing actual filename from URL
image_url_path_parse:
  reg_exp: ^(/file/id/)(.*)(/format/)(.*)$
  name_index: 1

output_lists:
  image_list:
    file: data/imagelist.csv
    encoding: utf-8-sig
    col_class: label
    col_image: image
  downloaded_list: data/downloaded.csv
  class_list: data/classes.csv
  grouped_class_list: data/grouped_classes.csv

image_download:
  folder: images/
  default_extension: jpg
  # if downloaded images don't have one of these extensions, they automatically get 'default_extension'
  expected_extensions:
    - jpg
    - jpeg

use_subdirs_as_classes: False

models:
  basename: corvidae_{model_architecture}
  folder: models/

#test_image_folder: tests/
test_image_folder: images/

log_folder: log/
