project_name: martin-collectie
project_root: /storage/data/martin-collectie/

# all other paths should be relative to project_root

dwca_infile:
  name: dwca/Occurrence.csv
  encoding: utf-8-sig

dwca_headers:
  id: catalogNumber
  name: scientificName
  images: associatedMedia

# reg exp for parsing actual filename from URL
image_url_path_parse:
  reg_exp: ^(/file/id/)(.*)(/format/)(.*)$
  name_index: 1
  
use_subdirs_as_classes: False

output_lists:
  image_list:
    file: data/imagelist.csv
    encoding: utf-8-sig
    col_class: label
    col_image: image
  downloaded_list: data/downloaded.csv
  class_list: data/classes.csv

image_download:
  folder: downloads/
  default_extension: jpg
  # if downloaded images don't have one of these extensions, they automatically get 'default_extension'
  expected_extensions:
    - jpg
    - jpeg

models:
  basename: martin_{model_architecture}
  folder: models/

test_image_folder: test/
log_folder: log/
