project_name: mnist
project_root: /storage/data/mnist/

# all other paths should be relative to project_root

#test_image_folder: tests/
test_image_folder: images/
log_folder: log/

images_per_class_minimum: 10

image_lists:
  all:
    file: data/imagelist.csv
    encoding: utf-8-sig
    col_class: label
    col_image: image
  downloaded:
    file: data/list.csv
  corrupt:
    file: data/corrupt_images.csv
  classes:
    file: data/classes.csv
  train:
    file: data/images_train.csv
  test:
    file: data/images_test.csv


image_download:
  folder: images/
  default_extension: jpg
  # if downloaded images don't have one of these extensions, they automatically get 'default_extension'
  expected_extensions:
    - jpg
    - jpeg

models:
  basename: mnist_{model_architecture}
  folder: models/




